# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "2017"
license = "MIT"
licenselink = "https://github.com/milleradagency/GOOD-Lunch/blob/master/LICENSE"
description = "Theme for 2017's THE LUNCH."
homepage = "thelunch.info"
tags = ["the lunch", "goodwill", "dallas", "2017"]
features = ["single page", "fundraiser", "event"]
min_version = 0.17

[author]
  name = "William Pansky"
  homepage = "http://williampansky.com"

# If porting an existing theme
[original]
  name = "Vimux"
  homepage = ""
  repo = "https://github.com/vimux/blank/"
